export const COLORS = [
  { name: '红色 / Red', value: '#FF3B30' },
  { name: '橙红 / Orange Red', value: '#FF6B35' },
  { name: '橙色 / Orange', value: '#FF9500' },
  { name: '金橙 / Gold', value: '#FFB340' },
  { name: '黄色 / Yellow', value: '#FFCC00' },
  { name: '柠檬黄 / Lemon', value: '#FFD60A' },
  { name: '黄绿 / Yellow Green', value: '#D4E157' },
  { name: '浅绿 / Light Green', value: '#8BC34A' },
  { name: '绿色 / Green', value: '#34C759' },
  { name: '翠绿 / Emerald', value: '#00C853' },
  { name: '青绿 / Teal Green', value: '#00BFA5' },
  { name: '青色 / Cyan', value: '#5AC8FA' },
  { name: '天蓝 / Sky Blue', value: '#64B5F6' },
  { name: '蓝色 / Blue', value: '#007AFF' },
  { name: '深蓝 / Deep Blue', value: '#2962FF' },
  { name: '靛蓝 / Indigo', value: '#5856D6' },
  { name: '紫蓝 / Purple Blue', value: '#7C4DFF' },
  { name: '紫色 / Purple', value: '#AF52DE' },
  { name: '深紫 / Deep Purple', value: '#AA00FF' },
  { name: '紫红 / Magenta', value: '#E040FB' },
  { name: '粉红 / Pink', value: '#FF2D55' },
  { name: '浅粉 / Light Pink', value: '#FF80AB' },
  { name: '玫红 / Rose', value: '#F50057' },
  { name: '珊瑚 / Coral', value: '#FF6E6E' },
  { name: '棕红 / Brown', value: '#8D6E63' },
  { name: '深棕 / Dark Brown', value: '#5D4037' },
  { name: '灰蓝 / Gray Blue', value: '#607D8B' },
  { name: '蓝灰 / Blue Gray', value: '#78909C' },
  { name: '橄榄 / Olive', value: '#827717' },
  { name: '深绿 / Dark Green', value: '#1B5E20' },
  { name: '海军蓝 / Navy', value: '#0D47A1' },
  { name: '酒红 / Wine', value: '#880E4F' },
]

export const APPLE_COLORS = {
  red: '#FF3B30',
  orange: '#FF9500',
  yellow: '#FFCC00',
  green: '#34C759',
  teal: '#5AC8FA',
  blue: '#007AFF',
  indigo: '#5856D6',
  purple: '#AF52DE',
  pink: '#FF2D55',
}

export const DARK_THEME = {
  background: '#000000',
  surface: '#1C1C1E',
  elevated: '#2C2C2E',
  separator: '#38383A',
  text: {
    primary: '#FFFFFF',
    secondary: '#EBEBF5',
    tertiary: 'rgba(235, 235, 245, 0.6)',
    quaternary: 'rgba(235, 235, 245, 0.3)',
  }
}
